# Generated by Django 5.1.7 on 2025-03-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trainingmodule_image_trainingmodule_video_url_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='The text of the answer choice.', max_length=200)),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct answer?')),
                ('question', models.ForeignKey(help_text='The question this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question')),
            ],
        ),
    ]
