# Generated by Django 5.1.7 on 2025-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_answer_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
